### ISSUE TITLE
z axis stopped working on gSHIELD

### ISSUE THREAD

**Issue by gembs1** [synthetos/grblShield#3]
CNC with 23Nema motors and arduino uno connected to gshield, running on 24v 10A power supply. It was working fine for a week; tonight the Zaxis stopped moving; I does get signal (if I send a command it does blink) and also the motor is working (tested a different one); I did not change or connected anything to it, it was at the end of a work and it quit working (the router made a mess on the way back to home since Z did not pull up!);  X and Y work fine.
is this an easy fix or do I need to buy a new driver? my guess is that the potentiometer is no good, but I have no way of proving it; (btw, I did move the potentiometer for this axis all the way and still nothing, just lights, no moving);
I tried reseting, powering off/on; moving the potentiometer all the way,  changing the motor, 
what should I do next?
Thank you for your help,

Eduardo

**Comment by ATAMYRKJE** [comment]
Hello gembs1,
sorry for your Z axis issue, did you try clean instal HEX files? i had a similar issue with y axis, then i setup my arduino back to zero and installed HEX files back, work fine now. Hope its help.

**Comment by gembs1** [comment]
Thanks atamyrkje, is a great idea, ...unfortunately It did not work for me; it still does everything else identically to all other axis (blinks and sounds), but no movement of the motor; I did reset the arduino and re-installed the grbl software, ... no change;
I might have to get a new driver...

**Comment by ril3y** [comment]
This sounds like the pot was over torqued?  You need to reply to the order email that you got from Synthetos to discuss further your options.

**Comment by gembs1** [comment]
I have a gShield with a nonworking axis; anyway I can send it back for repairs?
thanks

Eduardo Gembs
425-623-2283
